version: '3'

networks:
  blinko-network:
    driver: bridge

services:
  blinko-website:
    container_name: blinko-website
    build:
      context: .
      args:
        USE_MIRROR: "true"  
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:15433
      NEXT_PUBLIC_BASE_URL: http://localhost:15433
      NEXTAUTH_SECRET: my_ultra_secure_nextauth_secret
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - 15433:1111  # HOST:CONTAINER, use 1112 on your computer now
    healthcheck:
      test: ["CMD", "curl", "-f", "http://blinko-website:1111/"]
      interval: 30s 
      timeout: 10s  
      retries: 5
      start_period: 30s
    networks:
      - blinko-network

  postgres:
    image: postgres:14
    container_name: blinko-postgres
    restart: always
    ports:
      - 15432:5432  # Use 5433 on host machine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - blinko-network
